services:
  app1:
    image: ${APP_IMAGE}
    command: ["python3", "app.py"]
    environment:
      APP2_URL: http://app2:5001
      APP3_URL: http://app3:5002
    ports:
      - "5000:5000"
    depends_on:
      - app2
      - app3
    logging:
      driver: awslogs
      options:
        awslogs-region: eu-north-1
        awslogs-group: /cloud-residency/app
        awslogs-stream: app1

  app2:
    image: ${APP_IMAGE}
    command: ["python3", "app2.py"]
    volumes:
      - ./logs:/app/logs
    logging:
      driver: awslogs
      options:
        awslogs-region: eu-north-1
        awslogs-group: /cloud-residency/app
        awslogs-stream: app2

  app3:
    image: ${APP_IMAGE}
    command: ["python3", "app3.py"]
    ports:
      - "5002:5002"
    environment:
      SECRET_KEY: dev-change-me-now
      APP3_DB: /app/data/app3.db
    volumes:
      - ./data:/app/data
    logging:
      driver: awslogs
      options:
        awslogs-region: eu-north-1
        awslogs-group: /cloud-residency/app
        awslogs-stream: app3